// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

#include <iostream>
#include <string.h>
#include <numeric>

using namespace std;

char findTheDifference(string s, string t) {
    long int s1 = accumulate(s.begin(), s.end(), 0);
    long int s2 = accumulate(t.begin(), t.end(), 0);
    return static_cast<char>(s2 - s1);
}

int main() {
    cout << findTheDifference("abcd", "abcde") << endl;
    cout << findTheDifference("", "y") << endl;
}
